# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jbernard <jbernard@student.42quebec.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/14 01:39:48 by jbernard          #+#    #+#              #
#    Updated: 2023/03/14 01:46:18 by jbernard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone
FLAGS = -Wall -Werror -Wextra -std=c++98 -lc++

SRC = megaphone.cpp
CC = gcc

all : NAME

NAME :
	$(CC) $(FLAGS) $(SRC) -o $(NAME)

clean :
	@echo Nothing to be done
	
fclean :
	rm megaphone